baseURL: https://hackintoshpolska.pl/
languageCode: pl-pl
theme: docsy
title: hackintoshpolska
enableRobotsTXT: true
enableGitInfo: true
contentDir: content/pl
defaultContentLanguage: pl
copyright: Made with ğŸº Â© 2020 Hackintosh Polska.
  
params:
  socials:
  - title: Zobacz grupÄ™ na Facebooku!
    url: https://www.facebook.com/groups/hackintoshpolska
    icon: fa-facebook
    fa: true
  - title: DoÅ‚Ä…cz do nas na Discord!
    url: https://discord.com/invite/b6nttPd
    icon: fa-discord
    fa: true
  - title: Zobacz nasz GitHub!
    url: https://github.com/hackintoshpolska/hackintoshpolska-docs
    icon: fa-github
    fa: true
